### ISSUE TITLE
Not working if audit console is set to true

### ISSUE THREAD

**Issue by ibrunotome** [dev-partners/laravel-nova-auditable-log#1]
If `'console' => true` on config/audit.php, the package will fail with a message `TypeError: null is not an object (evaluating 'e.user.name')` because there is no user when auditing console.

**Comment by recycledbeans** [comment]
Thanks for reporting this, @ibrunotome. 

I'll try to push a fix for this today.

**Comment by recycledbeans** [comment]
Hi there, this issue has now been fixed (v1.0.1 available via composer).
