### ISSUE TITLE
Overriding policies

### ISSUE THREAD

**Issue by jonstavis** [dev-partners/laravel-nova-auditable-log#13]
The documentation indicates that it is possible to define an `audit_restore` Gate for a model so that this policy can be overridden.

However wherever I define this policy it seems like the only policy that is followed is the Gate defined at the top of the package's `ToolServiceProvider`

Where can I define this policy to override the package's default?

Thanks!

![Screen Shot 2020-04-07 at 1 59 54 PM](https://user-images.githubusercontent.com/1569236/78703402-14798a00-78d8-11ea-8fe0-5f393e858759.png)

**Comment by recycledbeans** [comment]
Hey @jonstavis, you are meant to define those two methods in the model's policy the same way you would define methods for Laravel Nova (viewAny, view, create, update, delete, forceDelete, restore).

Does this help? If not, maybe you can post the contents of your model policy?

Here's an example:

```php
    public function audit(User $user, Project $project)
    {
        return true;
    }

    public function audit_restore(User $user, Project $project)
    {
        return $user->id === $project->user_id;
    }
```

**Comment by jonstavis** [comment]
`AuthServiceProvider`:

````
protected $policies = [
        App\Models\MyModel::class => App\Policies\MyModelPolicy::class,
    ];
````

`MyModelPolicy`:

````
    public function audit_restore($loggedInUser, $resource) {
        return false;
    }
````

Thanks

**Comment by recycledbeans** [comment]
Okay, thanks for this. And the Nova resource you are trying to use this with correlates to this model, correct? For instance, if the Nova resource is related to the User model, these methods are in the UserPolicy?

**Comment by jonstavis** [comment]
Yes.

Strangely, if I comment out the Gate definition at the top of `ToolServiceProvider` my own defined policy works fine.  Perhaps it has to do with the ordering of the Service Providers?

In the meantime I seem to have figured out a way around this.  Defining my Gate in the `NovaServiceProvider->gate()` method does the trick for me!
