### ISSUE TITLE
attach able item

### ISSUE THREAD

**Issue by anditsung** [dev-partners/laravel-nova-auditable-log#15]
currently im using php v7
nova v2.12

when i attach a role to the user
it will not be record to the user audit

**Comment by recycledbeans** [comment]
Hey @anditsung I believe this has to do with the auditing package [owen-it/laravel-auditing](https://github.com/owen-it/laravel-auditing) that provides the underlying audit functionality, not the package in _this repository_, which displays those audit records in Laravel Nova.

It looks like auditing relationships has been something in the works for a while in that package, but has not yet been implemented as far as I can tell. [https://github.com/owen-it/laravel-auditing/issues/58](https://github.com/owen-it/laravel-auditing/issues/58)

I'm going to close this issue, but please respond if I'm incorrect or if I am misunderstanding the issue you are reporting.
