### ISSUE TITLE
Not working with fields in Nova Panel

### ISSUE THREAD

**Issue by u12206050** [dev-partners/laravel-nova-auditable-log#16]
When fields are changed that are contained within a Nova Panel then those fields don't show up when trying to restore, even though their values do exist in the audit log.

**Comment by recycledbeans** [comment]
Thanks, we'll look into this.

**Comment by recycledbeans** [comment]
Hey @u12206050 I wanted to follow up on this. I've tried replicating this issue based on your description, but haven't been able to do so. I actually think this may be related to #9 in that the restore functionality remains confusing. I'm working on an update to the package which should clear this up.

If you do not think this is the case, can you provide an example Nova resource setup in which this bug shows up?

**Comment by u12206050** [comment]
Hi, I think it was mainly due to the fact that I was using astrotomic/laravel-translatable which merges two tables into one model. I have forked and fixed it as you can see [here](https://github.com/dev-partners/laravel-nova-auditable-log/compare/master...u12206050:master)
Had to change the namespace in order for composer to use my version and not yours, but you are welcome to cherry pick from it.

Otherwise when I have time I can create a pull request, will just have to revert the namespaces thats all.
