### ISSUE TITLE
Nova 4 support (continued...)

### ISSUE THREAD

**Issue by miking7** [dev-partners/laravel-nova-auditable-log#27]
Hey @recycledbeans - thanks for merging @rklugman's [pull request](https://github.com/dev-partners/laravel-nova-auditable-log/pull/23) (which introduced Nova 4 support).  The main audit log is working well now - and this is awesome!  

Not sure if others are seeing the same issue that we're seeing, but unfortunately **the _RestoreAuditModal.vue_ modal still seems to be broken**... and from the we can tell it looks like Nova 4 has made a few kay changes to their implementation of Modals too.

A few notes below in case someone else gets a chance to dig into the issue sooner than we do:

* Changing the _\<modal\>_ to a _\<div\>_ on line 2 of _RestoreAuditModal.vue_ "partially unbreaks" the problem (the modal content becomes visible, but obviously in the wrong place in the DOM), and proves that the underlying logic is still working correctly.

* Doing a Nova 3-->4 diff of one of Nova's own modals (such as _ConfirmUploadRemovalModal.vue_) shows some key changes to how they're doing modals in Nova 4, and may be a good starting point for understanding what else is required.

**Comment by gbrits** [comment]
also eager to see Nova 4 support, is it in the works?

**Comment by gbrits** [comment]
Reverting doesn't appear to work - can't click the revert icon.

![Screen Shot 2022-08-03 at 12 23 54](https://user-images.githubusercontent.com/14840021/182523910-b1df3e6b-97a8-42ba-84b3-f9c1e63b53bb.png)

Also a bonus if we can customise the date?
