### ISSUE TITLE
Restore icon shows but is not clickable

### ISSUE THREAD

**Issue by GlennBags** [dev-partners/laravel-nova-auditable-log#30]
Have installed and created Gates for "audit" and "audit_restore", however, although my user sees the restore svg icon, it does not appear as clickable on hover, and nothing happens if I click anyway.

I have rebuild with npm. Is there some other configuration that I'm missing?

Using Nova 4.12 and laravel-auditing 13.5.
Auditable-log shows as 2.0.

**Comment by GlennBags** [comment]
Nobody?

**Comment by octoxan** [comment]
@GlennBags ever have any luck with this? Running into the same issue, but seems this package may be abandoned and can't find a good alternative =|

**Comment by GlennBags** [comment]
No, had no luck. 
As you said though, hadn't found a good alternative so we're retaining it atm for the history, as that's the primary interest.
