### ISSUE TITLE
Can you clarify which Auditable package this works with?

### ISSUE THREAD

**Issue by MikeCraig418** [dev-partners/laravel-nova-auditable-log#6]
I found https://github.com/yajra/laravel-auditable but I'm also aware of http://www.laravel-auditing.com/docs/9.0/installation

Thanks!

**Comment by recycledbeans** [comment]
Yep, no problem. It's the one discussed at laravel-auditing.com (owen-it/laravel-auditing). This is in the package's readme, but I can see how it's easy to miss.

I'll add the link to the laravel-auditing package in the description of this repo for others.

👍 Thank you
